### ISSUE TITLE
Weaver failing build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#957] opened 2023-05-16 19:45 UTC
Looks like boost is not being found on weaver now: https://sems-cdash-son.sandia.gov/cdash/build/48492/configure .  Is boostlib even needed now?  Do we need to update the boost module?

Tagging @mcarlson801 .

**Comment by bartgol** [comment] 2023-05-16 19:51
Weaver got completely revamped. They rolled a new set of modules, so it's likely boost is one of those that changed.

**Comment by bartgol** [comment] 2023-05-16 19:55
Ah, I missed the changes that went in, sorry.

**Comment by mcarlson801** [comment] 2023-05-16 19:55
The new boost module seems to be missing a few libraries, including `libboost_program_options.so`, that Trilinos needs. I'm going to reach out to weaver-help to see if it is intentional.

**Comment by ikalash** [comment] 2023-05-16 19:56
Sounds good, thanks @mcarlson801 !

**Comment by mcarlson801** [comment] 2023-05-17 19:13
Just heard back from weaver-help and it looks like they just didn't enable every boost library when they built via spack. They want to know which boost libraries we'd like them to enable and gave a list of all of the optional boost libraries below.

Does anyone know which libraries specifically we need for the Trilinos packages we use? Trilinos configuration fails because it can't find `program_options` but there might be others that fail once that's found. Although, maybe it would be better to suggest they just build with everything on to avoid re-visiting this issue in the future. Any thoughts?

```
Variants:
    Name [Default]             When                  Allowed values          Description
    =======================    ==================    ====================    ==============================================================================

    atomic [off]               –                    on, off                 Compile with atomic library
    build_system [generic]     –                    generic                 Build systems supported by the package
    chrono [off]               –                    on, off                 Compile with chrono library
    clanglibcpp [off]          --                    on, off                 Compile with clang libc++ instead of libstdc++
    container [off]            --                    on, off                 Compile with container library
    context [off]              --                    on, off                 Compile with context library
    context-impl [fcontext]    [@1.65.0:+context]    fcontext, ucontext,     Use the specified backend for boost-context
                                                     winfib                  
    contract [off]             –                    on, off                 Compile with contract library
    coroutine [off]            --                    on, off                 Compile with coroutine library
    cxxstd [98]                --                    98, 11, 14, 17, 2a      Use the specified C++ standard when building.
    date_time [off]            --                    on, off                 Compile with date_time library
    debug [off]                --                    on, off                 Switch to the debug version of Boost
    exception [off]            --                    on, off                 Compile with exception library
    fiber [off]                --                    on, off                 Compile with fiber library
    filesystem [off]           –                    on, off                 Compile with filesystem library
    graph [off]                --                    on, off                 Compile with graph library
    graph_parallel [off]       –                    on, off                 Compile with graph_parallel library
    icu [off]                  --                    on, off                 Build with Unicode and ICU suport
    iostreams [off]            --                    on, off                 Compile with iostreams library
    json [off]                 –                    on, off                 Compile with json library
    locale [off]               –                    on, off                 Compile with locale library
    log [off]                  --                    on, off                 Compile with log library
    math [off]                 –                    on, off                 Compile with math library
    mpi [off]                  --                    on, off                 Compile with mpi library
    multithreaded [on]         –                    on, off                 Build multi-threaded versions of libraries
    nowide [off]               –                    on, off                 Compile with nowide library
    numpy [off]                --                    on, off                 Build the Boost NumPy library (requires +python)
    pic [off]                  --                    on, off                 Generate position-independent code (PIC), useful for building static libraries
    program_options [off]      --                    on, off                 Compile with program_options library
    python [off]               –                    on, off                 Compile with python library
    random [off]               –                    on, off                 Compile with random library
    regex [off]                --                    on, off                 Compile with regex library
    serialization [off]        --                    on, off                 Compile with serialization library
    shared [on]                --                    on, off                 Additionally build shared libraries
    signals [off]              --                    on, off                 Compile with signals library
    singlethreaded [off]       –                    on, off                 Build single-threaded versions of libraries
    stacktrace [off]           –                    on, off                 Compile with stacktrace library
    system [off]               –                    on, off                 Compile with system library
    taggedlayout [off]         –                    on, off                 Augment library names with build options
    test [off]                 –                    on, off                 Compile with test library
    thread [off]               –                    on, off                 Compile with thread library
    timer [off]                --                    on, off                 Compile with timer library
    type_erasure [off]         –                    on, off                 Compile with type_erasure library
    versionedlayout [off]      --                    on, off                 Augment library layout with versioned subdirs
    visibility [hidden]        --                    global, protected,      Default symbol visibility in compiled libraries (1.69.0 or later)
                                                     hidden                  
    wave [off]                 –                    on, off                 Compile with wave library
```

**Comment by bartgol** [comment] 2023-05-17 21:13
I don't even know what part of trilinos uses boosts, so whatever you think is right.

**Comment by ikalash** [comment] 2023-05-18 03:10
I suggest looking here: https://github.com/sandialabs/Albany/wiki/Rhel6-using-Gcc (though it's out of date).  It used to be that you needed the following boost libs: signals,regex,filesystem,system,mpi,serialization,thread,program_options,exception  .

**Comment by mcarlson801** [comment] 2023-05-18 15:49
Thanks Irina, I just forwarded the list on to support so hopefully this should be fixed.

**Comment by ikalash** [comment] 2023-05-18 18:17
Thanks @mcarlson801 !  Let me know if any changes are needed on my side.

**Comment by ikalash** [comment] 2023-05-19 17:39
Seems that now the intel is not high enough on weaver: https://sems-cdash-son.sandia.gov/cdash/build/48581/configure .

**Comment by mcarlson801** [comment] 2023-05-19 19:20
I can't get on the sems-cdash-son site from DaaS for some reason but I think that's probably the Blake build. We don't build with intel on Weaver. I checked the logs though and it looks like the boost issue still isn't resolved on Weaver.

**Comment by bartgol** [comment] 2023-05-19 20:12
Yes, that's a blake build.Blake has old intel compilers, that kokkos does not support anymore, so the config craps out.

I think we've had those errors for a while.

**Comment by ikalash** [comment] 2023-05-19 20:14
Crap...  I clicked on the wrong line.  It's still the boost issue then for weaver: https://sems-cdash-son.sandia.gov/cdash/build/48598/configure .  Sorry about the confusion.

**Comment by ikalash** [comment] 2023-05-24 23:34
Excellent!  I will check the nightlies tomorrow to verify that things are back up on weaver.

**Comment by ikalash** [comment] 2023-05-25 17:45
Looks like now there are issues due to blas not being found: https://sems-cdash-son.sandia.gov/cdash/build/48813/configure .  Did the location of the blas library change?

**Comment by mcarlson801** [comment] 2023-05-25 18:27
I'll go check it out. I imagine the modules got updated again since it was building correctly previously for me once I pointed to my version of boost.

**Comment by mcarlson801** [comment] 2023-05-25 19:34
Yep, it looks like openblas got updated at some point. I fixed up the scripts for loading modules and configuring Trilinos both in the repo and the nightlyCDashWeaver directory. I confirmed Trilinos configures without error so this should be gone tomorrow, fingers crossed!

**Comment by ikalash** [comment] 2023-05-26 00:11
Thanks for fixing it!  I will check tomorrow.

**Comment by ikalash** [comment] 2023-05-26 20:27
Seems now there are netcdf related problems, sigh...

```
/usr/bin/ld: /projects/ppc64le-pwr9-rhel8/tpls/netcdf-c/4.9.0/gcc/8.5.0/openmpi/4.1.4/uzkucvn/lib/libnetcdf.a(cp_unix.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=48851

**Comment by bartgol** [comment] 2023-05-26 20:41
Are we linking the dl library? If not, it might just be that we need to add
```
-D CMAKE_EXE_LINKER_FLAGS:STRING="-ldl"    
```
to the config line in trilinos. We should need to do it for Albany as well, since it should get fwd-ed to Albany via target properties.

**Comment by mcarlson801** [comment] 2023-05-26 20:48
Gah, I only configured and didn't build so I missed this.

@bartgol Does `-D Kokkos_ENABLE_LIBDL:BOOL=ON \`  accomplish the same thing out of curiosity? We have that but not the flag you suggested. I wonder why it would be a problem now though and not before if this was the issue.

**Comment by bartgol** [comment] 2023-05-26 20:50
I would say no. The point that needs dl in the link Irina posted is in seacas applications, and I doubt that those link against kokkos. Maybe trilinois itself has a LIBDL cmake option?

**Comment by mcarlson801** [comment] 2023-05-26 21:24
Good call, Luca, that did it. 

Going to make sure there aren't any other surprises and then update the weaver dashboard.

**Comment by ikalash** [comment] 2023-05-26 22:17
Thanks guys!  Will check again tomorrow....

**Comment by ikalash** [comment] 2023-05-28 04:44
Well, there is some progress.  The code builds on weaver but most of the tests fail with the following error: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorNoDevice): no CUDA-capable device is detected /home/projects/albany/nightlyCDashWeaver/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:249
[weaver4:1012954] *** Process received signal ***
[weaver4:1012954] Signal: Aborted (6)
[weaver4:1012954] Signal code:  (-6)
```
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=48891

@mcarlson801 , do we need to maybe run in a special queue / on a special node.  Did you try running the tests when you created your own build on weaver with the new modules?

**Comment by bartgol** [comment] 2023-05-30 16:04
We've seen that error in our EAMxx testing. The issue is probably due to how you allocate the node. You need `bsub -gpu num=N ...`. The `-gpu num=N` is necessary to get the `CUDA_VISIBLE_DEVICES` env var set correctly. I bet if you printed the env you would see something like `CUDA_VISIBLE_DEVICES=` (empty).

**Comment by mcarlson801** [comment] 2023-05-30 16:06
Yep, I just updated the cronjob with the gpu flag and was about to reply. I ran ctest and it looks like things are running correctly now.

**Comment by mcarlson801** [comment] 2023-05-31 15:38
It seems the script I changed didn't fix this. @ikalash Is [cronjob-weaver11](https://github.com/sandialabs/Albany/blob/master/doc/dashboards/weaver.sandia.gov/cronjob-weaver11) the only script that allocates the job for the nightly tests on Weaver? I'm not sure why it still isn't getting GPUs allocated.

**Comment by ikalash** [comment] 2023-05-31 17:45
It's because I need to update the actual cronjob that is run on weaver.  I will do this now.

**Comment by ikalash** [comment] 2023-06-01 17:18
Seems we're down to just 21 failures now: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=49072 .  @mcarlson801 , did all the tests pass for you when you ran them on weaver?

**Comment by mcarlson801** [comment] 2023-06-01 18:23
Hmm.. so I tried replicating these failures and they don't always fail. I'll see if I can get some more info in a debugger.

**Comment by ikalash** [comment] 2023-06-01 20:29
So it is a Heisenbug...  those are such a pain!

**Comment by jewatkins** [comment] 2023-06-07 17:26
This is working now by switching to the old modules. Max and I have two tickets up in reference to the issues with the new modules & multi-node still not working.

**Closed by jewatkins** 2023-06-07 17:26 UTC

**Comment by jewatkins** [comment] 2023-06-07 17:33
btw, we shouldn't need the boost libs anymore. just the headers. Should probably update the config files...
