### ISSUE TITLE
CISM tests failing

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#928] opened 2023-04-12 16:16 UTC
The CISM tests are currently failing, following the DOFManager PR merge. It seems that these tests use two element blocks. We currently do not support two element blocks. If CISM tests must use 2 blocks, then we can't support them for now. We could disable these builds. Or maybe it's time to drop CISM support?

@ikalash @mperego what are your thoughts?

**Comment by ikalash** [comment] 2023-04-12 18:47
I was going to open this issue but you beat me to it.  I don't know why the tests have >1 element block...  I don't see why that would be necessary.  I will look into it.

**Comment by ikalash** [comment] 2023-04-13 03:54
I have fixed these tests.  The problem is that the CISM problems had no element blocks, not > 1 element block.  What this means is that the error message here is not correct: https://github.com/sandialabs/Albany/blob/master/src/disc/stk/Albany_STKDiscretization.cpp#L1032-L1033 .  I think we need a separate error message for the case when there are 0 element blocks.

Also, @bartgol , I assume you are testing MALI when you are making the changes to discretization?  The CISM interface is similar to the MPAS one so an error in CALI might translate to one in MALI.  I don't think that is the case here having inspected the MALI interface code but would be good to verify if that hasn't been done already.

**Comment by bartgol** [comment] 2023-04-13 16:05
Good catch!

To be clear, we should not allow meshes with 0 element blocks. Each mesh should have at least one element block, the whole mesh. Since currently we don't allow 2+ EBs, this seems a bit pointless, adding little to no information. However, a) we _may_ allow 2+ EBs later on, and b) we do use mesh parts relationship to restrict maps for distributed parameters, so we need the whole mesh to have a label.

**Comment by ikalash** [comment] 2023-04-13 16:21
@bartgol : I agree that 0 elt blocks are a no go.  Can I add an extra throw to handle this case, or did you want to?

**Comment by ikalash** [comment] 2023-04-13 16:41
Glad to hear you tested MALI @mperego .

**Comment by bartgol** [comment] 2023-04-13 17:04
It's a simple one liner fix, I think. I'll push straight to master, if that's ok.

**Comment by ikalash** [comment] 2023-04-13 17:06
> It's a simple one liner fix, I think. I'll push straight to master, if that's ok.

Please go ahead and do this!

**Comment by bartgol** [comment] 2023-04-13 17:16
Actually, I take it back. I now see that CismSTKMeshStruct _does_ call `addElementBlockInfo`, which does set `ebNames_` in the class. Therefore, the mesh struct _should_ have one element block.

How did you verify that they had no element blocks?

**Comment by ikalash** [comment] 2023-04-13 17:25
I added it last night, to fix the problem.

**Comment by bartgol** [comment] 2023-04-13 17:40
Ah, that makes sense. That should be enough then.

**Comment by ikalash** [comment] 2023-04-13 17:43
Yes, I'm just asking to add the additional throw in STKDiscretization for the 0 block case for the future.

**Comment by bartgol** [comment] 2023-04-13 19:02
Ah, I see.

**Comment by ikalash** [comment] 2023-04-13 21:40
I just added the logic/throw myself, just FYI.

**Comment by ikalash** [comment] 2023-04-15 15:34
I have fixed this.  Closing.

**Closed by ikalash** 2023-04-15 15:34 UTC
Labels: Discussion
